import type { Task } from "./types";

function due(dayOffset: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + dayOffset);
  return d.toISOString();
}

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Send proposal to Northwind Labs",
    description: "Finalize pricing and attach security appendix for enterprise tier.",
    priority: "high",
    status: "todo",
    dueDate: due(0),
    assignee: "Tanishq",
    companyName: "Northwind Labs",
    tags: ["Sales"],
  },
  {
    id: "t2",
    title: "Follow up with startup team",
    description: "Share investor deck updates and Q3 hiring plan.",
    priority: "medium",
    status: "in_progress",
    dueDate: due(1),
    assignee: "Tanishq",
    tags: ["Internal"],
  },
  {
    id: "t3",
    title: "Review subscription invoice",
    description: "Verify Razorpay line items against Pro plan renewal.",
    priority: "low",
    status: "todo",
    dueDate: due(3),
    assignee: "Tanishq",
    tags: ["Billing"],
  },
  {
    id: "t4",
    title: "Prep Meridian Health demo",
    description: "Configure HIPAA workspace sandbox and compliance checklist.",
    priority: "high",
    status: "in_progress",
    dueDate: due(0),
    assignee: "Alex Rivera",
    companyName: "Meridian Health",
    tags: ["Demo", "Healthcare"],
  },
  {
    id: "t5",
    title: "Update CRM pipeline stages",
    description: "Move Nova Finance deal to negotiation after pilot review.",
    priority: "medium",
    status: "todo",
    dueDate: due(2),
    assignee: "Sam Okonkwo",
    companyName: "Nova Finance",
    tags: ["CRM"],
  },
  {
    id: "t6",
    title: "Reply to Vertex API questions",
    description: "Document webhook payloads and rate limits for integration team.",
    priority: "high",
    status: "todo",
    dueDate: due(-1),
    assignee: "Sam Okonkwo",
    companyName: "Vertex Systems",
    tags: ["Technical"],
  },
  {
    id: "t7",
    title: "Schedule Orbit Media lunch",
    description: "Confirm Sightglass reservation for partnership discussion.",
    priority: "low",
    status: "todo",
    dueDate: due(5),
    assignee: "Tanishq",
    companyName: "Orbit Media",
    tags: ["Meeting"],
  },
  {
    id: "t8",
    title: "Draft automation release notes",
    description: "Summarize workflow editor and version history for changelog.",
    priority: "medium",
    status: "done",
    dueDate: due(-2),
    assignee: "Alex Rivera",
    tags: ["Product"],
  },
  {
    id: "t9",
    title: "Audit Gmail OAuth scopes",
    description: "Confirm least-privilege scopes before security review.",
    priority: "high",
    status: "done",
    dueDate: due(-3),
    assignee: "Tanishq",
    tags: ["Security"],
  },
  {
    id: "t10",
    title: "Onboard Brightline pilot users",
    description: "Send welcome sequence and connect first inbox.",
    priority: "medium",
    status: "todo",
    dueDate: due(4),
    assignee: "Alex Rivera",
    companyName: "Brightline",
    tags: ["Onboarding"],
  },
  {
    id: "t11",
    title: "Compile weekly metrics",
    description: "MRR, active users, and pipeline value for founder update.",
    priority: "high",
    status: "todo",
    dueDate: due(-1),
    assignee: "Tanishq",
    tags: ["Analytics"],
  },
  {
    id: "t12",
    title: "Refine landing page copy",
    description: "Align hero and pricing sections with new positioning.",
    priority: "low",
    status: "in_progress",
    dueDate: due(7),
    assignee: "Alex Rivera",
    tags: ["Marketing"],
  },
  {
    id: "t13",
    title: "Call Acme Corp about renewal",
    description: "Discuss seat expansion before contract end date.",
    priority: "high",
    status: "todo",
    dueDate: due(6),
    assignee: "Tanishq",
    companyName: "Acme Corp",
    tags: ["Sales"],
  },
  {
    id: "t14",
    title: "Test inbox AI reply tones",
    description: "QA professional, friendly, and concise tones across plans.",
    priority: "medium",
    status: "done",
    dueDate: due(0),
    assignee: "Sam Okonkwo",
    tags: ["QA"],
  },
];

export function getTaskById(id: string): Task | undefined {
  return MOCK_TASKS.find((t) => t.id === id);
}
