import type { Company, Contact, Deal } from "./types";

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    email: "sarah.chen@northwind.io",
    phone: "+1 (415) 555-0142",
    title: "VP of Operations",
    companyId: "co1",
    companyName: "Northwind Labs",
    status: "active",
    tags: ["Decision maker", "Enterprise"],
    lastContacted: "2026-06-24",
  },
  {
    id: "c2",
    name: "Marcus Webb",
    email: "marcus@brightpath.co",
    phone: "+1 (212) 555-0198",
    title: "Head of Growth",
    companyId: "co2",
    companyName: "Brightpath",
    status: "lead",
    tags: ["Inbound", "Demo scheduled"],
    lastContacted: "2026-06-22",
  },
  {
    id: "c3",
    name: "Priya Sharma",
    email: "priya.sharma@atlasventures.com",
    phone: "+91 98765 43210",
    title: "Managing Partner",
    companyId: "co3",
    companyName: "Atlas Ventures",
    status: "active",
    tags: ["Investor", "Warm intro"],
    lastContacted: "2026-06-20",
  },
  {
    id: "c4",
    name: "James Okafor",
    email: "j.okafor@stackline.dev",
    phone: "+44 20 7946 0958",
    title: "CTO",
    companyId: "co4",
    companyName: "Stackline",
    status: "lead",
    tags: ["Technical", "Trial"],
    lastContacted: "2026-06-18",
  },
  {
    id: "c5",
    name: "Elena Rodriguez",
    email: "elena@meridianhealth.org",
    phone: "+1 (617) 555-0173",
    title: "Director of IT",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "active",
    tags: ["Healthcare", "Compliance"],
    lastContacted: "2026-06-25",
  },
  {
    id: "c6",
    name: "Tom Hughes",
    email: "tom.hughes@oldclient.com",
    phone: "+1 (503) 555-0111",
    title: "Former Champion",
    companyId: "co6",
    companyName: "Cascade Retail",
    status: "inactive",
    tags: ["Churned"],
    lastContacted: "2026-01-10",
  },
  {
    id: "c7",
    name: "Aisha Khan",
    email: "aisha@novafinance.io",
    phone: "+1 (646) 555-0167",
    title: "Product Lead",
    companyId: "co7",
    companyName: "Nova Finance",
    status: "lead",
    tags: ["Fintech", "Pilot"],
    lastContacted: "2026-06-26",
  },
  {
    id: "c8",
    name: "David Park",
    email: "david.park@orbitmedia.com",
    phone: "+1 (310) 555-0134",
    title: "CEO",
    companyId: "co8",
    companyName: "Orbit Media",
    status: "active",
    tags: ["Agency", "Partner"],
    lastContacted: "2026-06-23",
  },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: "co1",
    name: "Northwind Labs",
    industry: "SaaS",
    size: "enterprise",
    website: "northwind.io",
    location: "San Francisco, CA",
    contactsCount: 4,
    openDeals: 2,
    totalPipeline: 185000,
  },
  {
    id: "co2",
    name: "Brightpath",
    industry: "Marketing",
    size: "smb",
    website: "brightpath.co",
    location: "New York, NY",
    contactsCount: 2,
    openDeals: 1,
    totalPipeline: 42000,
  },
  {
    id: "co3",
    name: "Atlas Ventures",
    industry: "Venture Capital",
    size: "enterprise",
    website: "atlasventures.com",
    location: "Mumbai, India",
    contactsCount: 3,
    openDeals: 0,
    totalPipeline: 0,
  },
  {
    id: "co4",
    name: "Stackline",
    industry: "Developer Tools",
    size: "startup",
    website: "stackline.dev",
    location: "London, UK",
    contactsCount: 2,
    openDeals: 1,
    totalPipeline: 28000,
  },
  {
    id: "co5",
    name: "Meridian Health",
    industry: "Healthcare",
    size: "enterprise",
    website: "meridianhealth.org",
    location: "Boston, MA",
    contactsCount: 5,
    openDeals: 1,
    totalPipeline: 95000,
  },
  {
    id: "co6",
    name: "Cascade Retail",
    industry: "E-commerce",
    size: "smb",
    website: "cascaderetail.com",
    location: "Portland, OR",
    contactsCount: 1,
    openDeals: 0,
    totalPipeline: 0,
  },
  {
    id: "co7",
    name: "Nova Finance",
    industry: "Fintech",
    size: "startup",
    website: "novafinance.io",
    location: "New York, NY",
    contactsCount: 2,
    openDeals: 1,
    totalPipeline: 36000,
  },
  {
    id: "co8",
    name: "Orbit Media",
    industry: "Media & Agency",
    size: "smb",
    website: "orbitmedia.com",
    location: "Los Angeles, CA",
    contactsCount: 3,
    openDeals: 1,
    totalPipeline: 54000,
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: "d1",
    title: "Northwind — Enterprise rollout",
    companyId: "co1",
    companyName: "Northwind Labs",
    contactId: "c1",
    contactName: "Sarah Chen",
    stage: "negotiation",
    value: 120000,
    probability: 75,
    closeDate: "2026-07-15",
    owner: "Tanishq",
  },
  {
    id: "d2",
    title: "Brightpath — Growth team seats",
    companyId: "co2",
    companyName: "Brightpath",
    contactId: "c2",
    contactName: "Marcus Webb",
    stage: "proposal",
    value: 42000,
    probability: 55,
    closeDate: "2026-07-30",
    owner: "Tanishq",
  },
  {
    id: "d3",
    title: "Stackline — Dev tools integration",
    companyId: "co4",
    companyName: "Stackline",
    contactId: "c4",
    contactName: "James Okafor",
    stage: "qualified",
    value: 28000,
    probability: 40,
    closeDate: "2026-08-12",
    owner: "Tanishq",
  },
  {
    id: "d4",
    title: "Meridian — HIPAA-compliant workspace",
    companyId: "co5",
    companyName: "Meridian Health",
    contactId: "c5",
    contactName: "Elena Rodriguez",
    stage: "proposal",
    value: 95000,
    probability: 60,
    closeDate: "2026-08-01",
    owner: "Tanishq",
  },
  {
    id: "d5",
    title: "Nova Finance — Pilot expansion",
    companyId: "co7",
    companyName: "Nova Finance",
    contactId: "c7",
    contactName: "Aisha Khan",
    stage: "lead",
    value: 36000,
    probability: 25,
    closeDate: "2026-09-05",
    owner: "Tanishq",
  },
  {
    id: "d6",
    title: "Orbit Media — Agency partnership",
    companyId: "co8",
    companyName: "Orbit Media",
    contactId: "c8",
    contactName: "David Park",
    stage: "qualified",
    value: 54000,
    probability: 45,
    closeDate: "2026-07-22",
    owner: "Tanishq",
  },
  {
    id: "d7",
    title: "Northwind — Add-on AI credits",
    companyId: "co1",
    companyName: "Northwind Labs",
    contactId: "c1",
    contactName: "Sarah Chen",
    stage: "won",
    value: 65000,
    probability: 100,
    closeDate: "2026-05-18",
    owner: "Tanishq",
  },
  {
    id: "d8",
    title: "Cascade — Renewal",
    companyId: "co6",
    companyName: "Cascade Retail",
    contactId: "c6",
    contactName: "Tom Hughes",
    stage: "lost",
    value: 18000,
    probability: 0,
    closeDate: "2026-04-02",
    owner: "Tanishq",
  },
];

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatDate(date: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(date + "T12:00:00"));
}
