import type { Company, Contact, Deal } from "./types";

export const CONTACT_SEEDS: Omit<Contact, "owner">[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    email: "sarah.chen@northwind.io",
    phone: "+1 (415) 555-0142",
    title: "VP of Operations",
    companyId: "co1",
    companyName: "Northwind Labs",
    status: "active",
    tags: ["Decision maker", "Enterprise"],
    lastContacted: "2026-06-24",
    linkedin: "linkedin.com/in/sarahchen",
    notes:
      "Primary champion for enterprise rollout. Prefers async updates via email. Decision expected Q3.",
    aiLeadScore: 92,
  },
  {
    id: "c2",
    name: "Marcus Webb",
    email: "marcus@brightpath.co",
    phone: "+1 (212) 555-0198",
    title: "Head of Growth",
    companyId: "co2",
    companyName: "Brightpath",
    status: "lead",
    tags: ["Inbound", "Demo scheduled"],
    lastContacted: "2026-06-22",
    linkedin: "linkedin.com/in/marcuswebb",
    notes: "Inbound from Product Hunt launch. Demo scheduled for next week.",
    aiLeadScore: 71,
  },
  {
    id: "c3",
    name: "Priya Sharma",
    email: "priya.sharma@atlasventures.com",
    phone: "+91 98765 43210",
    title: "Managing Partner",
    companyId: "co3",
    companyName: "Atlas Ventures",
    status: "active",
    tags: ["Investor", "Warm intro"],
    lastContacted: "2026-06-20",
    linkedin: "linkedin.com/in/priyasharma",
    notes: "Warm intro from portfolio company. Exploring workspace for deal team.",
    aiLeadScore: 68,
  },
  {
    id: "c4",
    name: "James Okafor",
    email: "j.okafor@stackline.dev",
    phone: "+44 20 7946 0958",
    title: "CTO",
    companyId: "co4",
    companyName: "Stackline",
    status: "lead",
    tags: ["Technical", "Trial"],
    lastContacted: "2026-06-18",
    linkedin: "linkedin.com/in/jamesokafor",
    notes: "Technical evaluation in progress. API integration is key requirement.",
    aiLeadScore: 58,
  },
  {
    id: "c5",
    name: "Elena Rodriguez",
    email: "elena@meridianhealth.org",
    phone: "+1 (617) 555-0173",
    title: "Director of IT",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "active",
    tags: ["Healthcare", "Compliance"],
    lastContacted: "2026-06-25",
    linkedin: "linkedin.com/in/elenarodriguez",
    notes: "HIPAA compliance review underway. Legal team involved in procurement.",
    aiLeadScore: 85,
  },
  {
    id: "c6",
    name: "Tom Hughes",
    email: "tom.hughes@oldclient.com",
    phone: "+1 (503) 555-0111",
    title: "Former Champion",
    companyId: "co6",
    companyName: "Cascade Retail",
    status: "inactive",
    tags: ["Churned"],
    lastContacted: "2026-01-10",
    linkedin: "linkedin.com/in/tomhughes",
    notes: "Account churned due to budget cuts. Re-engage in Q4.",
    aiLeadScore: 18,
  },
  {
    id: "c7",
    name: "Aisha Khan",
    email: "aisha@novafinance.io",
    phone: "+1 (646) 555-0167",
    title: "Product Lead",
    companyId: "co7",
    companyName: "Nova Finance",
    status: "lead",
    tags: ["Fintech", "Pilot"],
    lastContacted: "2026-06-26",
    linkedin: "linkedin.com/in/aishakhan",
    notes: "Running 30-day pilot with 5 seats. Expansion discussion in 2 weeks.",
    aiLeadScore: 64,
  },
  {
    id: "c8",
    name: "David Park",
    email: "david.park@orbitmedia.com",
    phone: "+1 (310) 555-0134",
    title: "CEO",
    companyId: "co8",
    companyName: "Orbit Media",
    status: "active",
    tags: ["Agency", "Partner"],
    lastContacted: "2026-06-23",
    linkedin: "linkedin.com/in/davidpark",
    notes: "Interested in agency partnership program. Fast decision maker.",
    aiLeadScore: 79,
  },
  {
    id: "c9",
    name: "Alex Kim",
    email: "alex.kim@northwind.io",
    phone: "+1 (415) 555-0188",
    title: "Engineering Lead",
    companyId: "co1",
    companyName: "Northwind Labs",
    status: "active",
    tags: ["Technical"],
    lastContacted: "2026-06-21",
    linkedin: "linkedin.com/in/alexkim",
    notes: "Owns technical validation. Paired with Sarah on rollout.",
    aiLeadScore: 74,
  },
  {
    id: "c10",
    name: "Rita Voss",
    email: "rita.voss@northwind.io",
    phone: "+1 (415) 555-0191",
    title: "Procurement Manager",
    companyId: "co1",
    companyName: "Northwind Labs",
    status: "active",
    tags: ["Procurement"],
    lastContacted: "2026-06-19",
    linkedin: "linkedin.com/in/ritavoss",
    notes: "Handles contract and vendor onboarding.",
    aiLeadScore: 61,
  },
  {
    id: "c11",
    name: "Noah Patel",
    email: "noah.patel@northwind.io",
    phone: "+1 (415) 555-0177",
    title: "CFO",
    companyId: "co1",
    companyName: "Northwind Labs",
    status: "lead",
    tags: ["Finance", "Approver"],
    lastContacted: "2026-06-15",
    linkedin: "linkedin.com/in/noahpatel",
    notes: "Final budget sign-off required for enterprise deal.",
    aiLeadScore: 55,
  },
  {
    id: "c12",
    name: "Jen Liu",
    email: "jen.liu@brightpath.co",
    phone: "+1 (212) 555-0201",
    title: "Marketing Ops",
    companyId: "co2",
    companyName: "Brightpath",
    status: "active",
    tags: ["Operations"],
    lastContacted: "2026-06-20",
    linkedin: "linkedin.com/in/jenliu",
    notes: "Day-to-day user champion for marketing team rollout.",
    aiLeadScore: 52,
  },
  {
    id: "c13",
    name: "Omar Hassan",
    email: "omar@atlasventures.com",
    phone: "+91 98765 43211",
    title: "Associate",
    companyId: "co3",
    companyName: "Atlas Ventures",
    status: "lead",
    tags: ["Research"],
    lastContacted: "2026-06-17",
    linkedin: "linkedin.com/in/omarhassan",
    notes: "Conducting vendor comparison for Priya.",
    aiLeadScore: 44,
  },
  {
    id: "c14",
    name: "Lisa Tran",
    email: "lisa.tran@atlasventures.com",
    phone: "+91 98765 43212",
    title: "Operations Director",
    companyId: "co3",
    companyName: "Atlas Ventures",
    status: "active",
    tags: ["Operations"],
    lastContacted: "2026-06-14",
    linkedin: "linkedin.com/in/lisatran",
    notes: "Owns internal tooling budget for portfolio support team.",
    aiLeadScore: 49,
  },
  {
    id: "c15",
    name: "Chris Bell",
    email: "chris@stackline.dev",
    phone: "+44 20 7946 0960",
    title: "Product Manager",
    companyId: "co4",
    companyName: "Stackline",
    status: "active",
    tags: ["Product"],
    lastContacted: "2026-06-16",
    linkedin: "linkedin.com/in/chrisbell",
    notes: "Coordinates trial feedback from dev team.",
    aiLeadScore: 56,
  },
  {
    id: "c16",
    name: "Dr. Amy Walsh",
    email: "amy.walsh@meridianhealth.org",
    phone: "+1 (617) 555-0180",
    title: "Chief Medical Officer",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "active",
    tags: ["Executive", "Healthcare"],
    lastContacted: "2026-06-23",
    linkedin: "linkedin.com/in/amywalsh",
    notes: "Executive sponsor. Cares about clinician workflow impact.",
    aiLeadScore: 88,
  },
  {
    id: "c17",
    name: "Ryan Cooper",
    email: "ryan.cooper@meridianhealth.org",
    phone: "+1 (617) 555-0181",
    title: "Security Officer",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "active",
    tags: ["Security", "Compliance"],
    lastContacted: "2026-06-22",
    linkedin: "linkedin.com/in/ryancooper",
    notes: "Leading security questionnaire and BAA review.",
    aiLeadScore: 72,
  },
  {
    id: "c18",
    name: "Maria Santos",
    email: "maria.santos@meridianhealth.org",
    phone: "+1 (617) 555-0182",
    title: "Clinical Operations",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "lead",
    tags: ["Clinical"],
    lastContacted: "2026-06-18",
    linkedin: "linkedin.com/in/mariasantos",
    notes: "Pilot user group coordinator for 3 hospital sites.",
    aiLeadScore: 60,
  },
  {
    id: "c19",
    name: "Kevin Brooks",
    email: "kevin.brooks@meridianhealth.org",
    phone: "+1 (617) 555-0183",
    title: "VP Finance",
    companyId: "co5",
    companyName: "Meridian Health",
    status: "active",
    tags: ["Finance"],
    lastContacted: "2026-06-12",
    linkedin: "linkedin.com/in/kevinbrooks",
    notes: "Budget holder for digital transformation initiatives.",
    aiLeadScore: 66,
  },
  {
    id: "c20",
    name: "Sophie Lee",
    email: "sophie@novafinance.io",
    phone: "+1 (646) 555-0168",
    title: "Engineering Manager",
    companyId: "co7",
    companyName: "Nova Finance",
    status: "active",
    tags: ["Technical"],
    lastContacted: "2026-06-24",
    linkedin: "linkedin.com/in/sophielee",
    notes: "Technical counterpart to Aisha on pilot integration.",
    aiLeadScore: 57,
  },
  {
    id: "c21",
    name: "Jordan Miles",
    email: "jordan@orbitmedia.com",
    phone: "+1 (310) 555-0135",
    title: "Client Director",
    companyId: "co8",
    companyName: "Orbit Media",
    status: "active",
    tags: ["Agency"],
    lastContacted: "2026-06-21",
    linkedin: "linkedin.com/in/jordanmiles",
    notes: "Manages client accounts that would use Actora under partnership.",
    aiLeadScore: 63,
  },
  {
    id: "c22",
    name: "Taylor Reed",
    email: "taylor@orbitmedia.com",
    phone: "+1 (310) 555-0136",
    title: "Operations Lead",
    companyId: "co8",
    companyName: "Orbit Media",
    status: "lead",
    tags: ["Operations"],
    lastContacted: "2026-06-19",
    linkedin: "linkedin.com/in/taylorreed",
    notes: "Evaluating workflow automation for agency ops team.",
    aiLeadScore: 48,
  },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: "co1",
    name: "Northwind Labs",
    industry: "SaaS",
    size: "enterprise",
    status: "active",
    website: "northwind.io",
    address: "548 Market St, Suite 420, San Francisco, CA 94104",
    notes:
      "Series C SaaS company expanding GTM team. Strong product-market fit in dev tools vertical. Multi-year contract potential.",
    revenue: 48000000,
    employeeCount: 320,
    owner: "Tanishq",
    aiScore: 91,
    openDeals: 2,
    totalPipeline: 185000,
  },
  {
    id: "co2",
    name: "Brightpath",
    industry: "Marketing",
    size: "smb",
    status: "active",
    website: "brightpath.co",
    address: "350 Fifth Avenue, New York, NY 10118",
    notes:
      "Fast-growing marketing agency. Inbound interest after Product Hunt feature. Price-sensitive but high growth.",
    revenue: 8500000,
    employeeCount: 45,
    owner: "Alex Rivera",
    aiScore: 72,
    openDeals: 1,
    totalPipeline: 42000,
  },
  {
    id: "co3",
    name: "Atlas Ventures",
    industry: "Venture Capital",
    size: "enterprise",
    status: "prospect",
    website: "atlasventures.com",
    address: "Bandra Kurla Complex, Mumbai, Maharashtra 400051",
    notes:
      "Top-tier VC firm evaluating workspace for deal team and portfolio support. Long sales cycle expected.",
    revenue: 120000000,
    employeeCount: 85,
    owner: "Tanishq",
    aiScore: 65,
    openDeals: 0,
    totalPipeline: 0,
  },
  {
    id: "co4",
    name: "Stackline",
    industry: "Developer Tools",
    size: "startup",
    status: "active",
    website: "stackline.dev",
    address: "25 Old Street, London EC1V 9DD, UK",
    notes:
      "Developer tools startup in active trial. API-first integration is critical path to close.",
    revenue: 2100000,
    employeeCount: 18,
    owner: "Alex Rivera",
    aiScore: 59,
    openDeals: 1,
    totalPipeline: 28000,
  },
  {
    id: "co5",
    name: "Meridian Health",
    industry: "Healthcare",
    size: "enterprise",
    status: "active",
    website: "meridianhealth.org",
    address: "200 Healthcare Blvd, Boston, MA 02115",
    notes:
      "Regional health network with strict compliance requirements. High-value enterprise opportunity with HIPAA needs.",
    revenue: 890000000,
    employeeCount: 4200,
    owner: "Tanishq",
    aiScore: 88,
    openDeals: 1,
    totalPipeline: 95000,
  },
  {
    id: "co6",
    name: "Cascade Retail",
    industry: "E-commerce",
    size: "smb",
    status: "churned",
    website: "cascaderetail.com",
    address: "1200 SW Morrison St, Portland, OR 97205",
    notes:
      "Former customer — churned Q1 due to budget reallocation. Monitor for re-engagement opportunity.",
    revenue: 12000000,
    employeeCount: 62,
    owner: "Sam Okonkwo",
    aiScore: 24,
    openDeals: 0,
    totalPipeline: 0,
  },
  {
    id: "co7",
    name: "Nova Finance",
    industry: "Fintech",
    size: "startup",
    status: "active",
    website: "novafinance.io",
    address: "55 Broadway, New York, NY 10006",
    notes:
      "Early-stage fintech in pilot phase. Strong technical team, evaluating expansion to full org.",
    revenue: 3200000,
    employeeCount: 24,
    owner: "Sam Okonkwo",
    aiScore: 62,
    openDeals: 1,
    totalPipeline: 36000,
  },
  {
    id: "co8",
    name: "Orbit Media",
    industry: "Media & Agency",
    size: "smb",
    status: "active",
    website: "orbitmedia.com",
    address: "10250 Constellation Blvd, Los Angeles, CA 90067",
    notes:
      "Creative agency exploring partnership model. CEO-driven decision, fast-moving.",
    revenue: 15000000,
    employeeCount: 78,
    owner: "Alex Rivera",
    aiScore: 76,
    openDeals: 1,
    totalPipeline: 54000,
  },
];

export const MOCK_CONTACTS: Contact[] = CONTACT_SEEDS.map((contact) => ({
  ...contact,
  owner:
    MOCK_COMPANIES.find((company) => company.id === contact.companyId)?.owner ??
    "Tanishq",
}));

export const MOCK_DEALS: Deal[] = [
  {
    id: "d1",
    title: "Northwind — Enterprise rollout",
    companyId: "co1",
    companyName: "Northwind Labs",
    contactId: "c1",
    contactName: "Sarah Chen",
    stage: "negotiation",
    value: 120000,
    probability: 75,
    closeDate: "2026-07-15",
    owner: "Tanishq",
  },
  {
    id: "d2",
    title: "Brightpath — Growth team seats",
    companyId: "co2",
    companyName: "Brightpath",
    contactId: "c2",
    contactName: "Marcus Webb",
    stage: "proposal",
    value: 42000,
    probability: 55,
    closeDate: "2026-07-30",
    owner: "Tanishq",
  },
  {
    id: "d3",
    title: "Stackline — Dev tools integration",
    companyId: "co4",
    companyName: "Stackline",
    contactId: "c4",
    contactName: "James Okafor",
    stage: "qualified",
    value: 28000,
    probability: 40,
    closeDate: "2026-08-12",
    owner: "Tanishq",
  },
  {
    id: "d4",
    title: "Meridian — HIPAA-compliant workspace",
    companyId: "co5",
    companyName: "Meridian Health",
    contactId: "c5",
    contactName: "Elena Rodriguez",
    stage: "proposal",
    value: 95000,
    probability: 60,
    closeDate: "2026-08-01",
    owner: "Tanishq",
  },
  {
    id: "d5",
    title: "Nova Finance — Pilot expansion",
    companyId: "co7",
    companyName: "Nova Finance",
    contactId: "c7",
    contactName: "Aisha Khan",
    stage: "lead",
    value: 36000,
    probability: 25,
    closeDate: "2026-09-05",
    owner: "Tanishq",
  },
  {
    id: "d6",
    title: "Orbit Media — Agency partnership",
    companyId: "co8",
    companyName: "Orbit Media",
    contactId: "c8",
    contactName: "David Park",
    stage: "qualified",
    value: 54000,
    probability: 45,
    closeDate: "2026-07-22",
    owner: "Tanishq",
  },
  {
    id: "d7",
    title: "Northwind — Add-on AI credits",
    companyId: "co1",
    companyName: "Northwind Labs",
    contactId: "c1",
    contactName: "Sarah Chen",
    stage: "won",
    value: 65000,
    probability: 100,
    closeDate: "2026-05-18",
    owner: "Tanishq",
  },
  {
    id: "d8",
    title: "Cascade — Renewal",
    companyId: "co6",
    companyName: "Cascade Retail",
    contactId: "c6",
    contactName: "Tom Hughes",
    stage: "lost",
    value: 18000,
    probability: 0,
    closeDate: "2026-04-02",
    owner: "Tanishq",
  },
];

export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function formatRevenue(value: number): string {
  if (value >= 1_000_000_000) {
    return `$${(value / 1_000_000_000).toFixed(1)}B`;
  }
  if (value >= 1_000_000) {
    return `$${(value / 1_000_000).toFixed(1)}M`;
  }
  if (value >= 1_000) {
    return `$${(value / 1_000).toFixed(0)}K`;
  }
  return formatCurrency(value);
}

export function formatDate(date: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(date + "T12:00:00"));
}

export function formatEmployeeCount(count: number): string {
  return new Intl.NumberFormat("en-US").format(count);
}
